### ISSUE TITLE
在上一个问题中，我对decode进行调，出现了乱码

### ISSUE THREAD

**Issue by taylorSZSS** [Kevin0z0/koutufenfang-sender#3]
在utf-8后取消了默认的严格条件，改成  i.decode("utf-8","ignore")，这样解决了上诉的异常，但是发送的中午变成了乱码。第一次接触这个，求解答

**Comment by Kevin0z0** [comment]
应该是你文本编码的问题，我只测试了gbk和ansi的

**Comment by Kevin0z0** [comment]
我更新了一下，你再试试

**Comment by taylorSZSS** [comment]
在setting文件中改成ma.txt，提示("[!] 无法使用此文本,请使用utf8编码的文本")。

**Comment by taylorSZSS** [comment]
用kua.txt是正常的。why,这两个文本还是不同格式的嘛？

**Comment by Kevin0z0** [comment]
kua是utf8的，ma是gb18030的，但是python识别成了gb2312，怪不得转不了，直接把gb开头的都以gbk的方式转码就应该可以了

**Comment by taylorSZSS** [comment]
可以了，我对文本进行格式转换就行了，谢谢大哥解答。
